# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Unittests

on:
  pull_request:

  push:
    branches:
      - main
      - release_*

jobs:
  test:
    name: Run JDK ${{ matrix.jdk-version }} tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        jdk-version: ["11", "18", "19"]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.jdk-version }}
          distribution: 'temurin'
          cache: maven

      - name: Test for JDK ${{ matrix.jdk-version }}
        run: mvn --batch-mode --update-snapshots test jacoco:report
      - name: Coveralls Parallel
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: run-jdk${{ matrix.jdk-version }}
          parallel: true

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
