name: Unittests

on:
  pull_request:

  push:
    branches:
      - main
      - release_*

jobs:
  test:
    name: Run JDK ${{ matrix.jdk-version }} tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        jdk-version: [ "19" ]

    steps:
      - name: 🧺 Checkout Repository Code
        uses: actions/checkout@v3
      - name: 🛠 Set up JDK ${{ matrix.jdk-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.jdk-version }}
          distribution: 'temurin'
          cache: maven

      - name: 🚀 Generate Coverage Report for JDK ${{ matrix.jdk-version }}
        run:  mvn clean test jacoco:report

      - name: Run coveralls-python for JDK ${{ matrix.jdk-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: jdk-${{ matrix.jdk-version }}
          COVERALLS_PARALLEL: true
        run: |
          pip3 install --upgrade pip
          pip3 install --upgrade setuptools
          pip3 install --upgrade coveralls
          /home/runner/.local/bin/coveralls --service=github --merge=./target/jacoco-report/jacoco.xml

  coveralls-finish:
    name: Finish coveralls-python
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Finished
        run: |
          pip3 install --upgrade pip
          pip3 install --upgrade setuptools
          pip3 install --upgrade coveralls
          /home/runner/.local/bin/coveralls --finish --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
